services:
  - type: web
    name: edulinkx-backend
    rootDir: Backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20.0.0
